---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Template the Vault config
      template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
      notify: restart vault
  handlers:
    - name: restart vault
      systemd:
        name: vault
        state: restarted
        daemon_reload: true
